; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32dev

[env:esp32devdeb]
; Info
; pio device list
;
; Clean previous builds (important!)
; pio run -e esp32devdeb --target clean
;
; Build with verbose output to see details
; pio run -e esp32devdeb
;
; Upload
; pio run -e esp32devdeb --target upload
;
; Debug
; LD_LIBRARY_PATH=/opt/python2.7/lib pio debug -e esp32devdeb --interface gdb
;
; target extended-remote /dev/ttyACM0
;
; info mem
; info thread
; info functions loop_time
;

platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
	robtillaart/DS18B20@^0.1.14
	bblanchon/ArduinoJson@6.21.5
	https://github.com/Evgen2/AutoConnect@^1.4.6
	https://github.com/Evgen2/arduino-home-assistant
build_flags = 
	-Wall
    -DSERIAL_DEBUG=1
    -DCORE_DEBUG_LEVEL=5	
;	-DAC_DEBUG
;	-DARDUINOHA_DEBUG
    -DDISABLE_ARDUINO_CORE_WARNINGS
	-g                      ; Generate debug symbols
    -Og                     ; Optimize for debugging
monitor_speed = 115200
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
monitor_filters = default, log2file
;monitor_filters = debug
build_type = debug
debug_tool = esp-prog
debug_port = /dev/ttyACM0
;debug_server =
;    executable = ~/.platformio/packages/tool-openocd-esp32/bin/openocd
;	executable = openocd
;    arguments = -f esp32devdeb.cfg ;-f board/esp-wroom-32.cfg
debug_init_break = tbreak setup

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
	robtillaart/DS18B20@^0.1.14
	bblanchon/ArduinoJson@6.21.5
	https://github.com/Evgen2/AutoConnect@^1.4.6
	https://github.com/Evgen2/arduino-home-assistant
build_flags = 
	-Wall
	-DCORE_DEBUG_LEVEL=0
;   -DCORE_DEBUG_LEVEL=5	
;	-DAC_DEBUG
;	-DARDUINOHA_DEBUG
monitor_speed = 115200
upload_port = COM[2]
monitor_port = COM[2]
monitor_filters = default, log2file

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
lib_deps = 
	robtillaart/DS18B20@^0.1.14
	bblanchon/ArduinoJson@6.21.5
	knolleary/PubSubClient@^2.8
	https://github.com/Evgen2/AutoConnect@^1.4.3
	https://github.com/Evgen2/arduino-home-assistant
build_flags = 
	-DB_NODEMSU
	-DAUTOCONNECT_NOUSE_JSON
	-DEX_ARDUINOHA_BUTTON
	-DEX_ARDUINOHA_CAMERA
	-DEX_ARDUINOHA_COVER
	-DEX_ARDUINOHA_DEVICE_TRACKER
	-DEX_ARDUINOHA_DEVICE_TRIGGER
	-DEX_ARDUINOHA_FAN
	-DEX_ARDUINOHA_LIGHT
	-DEX_ARDUINOHA_LOCK
	-DEX_ARDUINOHA_SCENE
	-DEX_ARDUINOHA_SELECT
	-DEX_ARDUINOHA_TAG_SCANNER
monitor_speed = 115200
upload_port = COM[9]
monitor_port = COM[9]
